### ISSUE TITLE
Document how to maintain the site

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#10]

**Comment by gbinal** [comment]
- [Homepage, top right blogposts](https://github.com/GSA/gsa.github.io/blob/master/index.html#L32-L54)
- [Other Developer Hubs - Developer Page](https://github.com/GSA/gsa.github.io/blob/master/developer/index.html#L32-L55)
- [List of APIs - Developer Page](https://github.com/GSA/gsa.github.io/blob/master/developer/index.html#L63-L199)
- [Other Data Resources - Data Page](https://github.com/GSA/gsa.github.io/blob/master/data1/index.html#L32-L43)

**Comment by saracope** [comment]
Closing. Will not fix on this site as it is being retired.
