### ISSUE TITLE
Set up HTTPS

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#13]

**Comment by afeld** [comment]
Note that this isn't possible with GitHub Pages, unless you put a CDN in front of it.

> HTTPS is not supported for GitHub Pages using custom domains.

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by saracope** [comment]
We're actually going to be hosting the new site on Federalist.

**Comment by saracope** [comment]
Closing out, will not fix here as we are retiring the site.
