### ISSUE TITLE
deprecate legacy developer page 

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#18]
After #16 is closed, request the following:  

1) Change the redirects for www.gsa.gov/developer, gsa.gov/developer, www.gsa.gov/developers, and gsa.gov/developers to direct visitors to open.gsa.gov/developer 
2) Remove the content on http://gsa.gov/portal/content/144479 and http://gsa.gov/portal/content/181599
3) Set up 301 redirects from http://gsa.gov/portal/content/144479 and http://gsa.gov/portal/content/181599 to open.gsa.gov/developer

Patrick needs to check on 301 redirects .. if it is possible.

**Comment by gbinal** [comment]
I just realized that the GSA developer page is also represented http://gsa.gov/portal/content/181599.  Updating the above to reflect that.

**Comment by gbinal** [comment]
**Update**: 

2/3 of this is completed.  Steps 1 and 2 above are completed, but the redirects weren't set up.  This is bad, since some folks may have bookmarked http://gsa.gov/portal/content/144479, which now 404s.  

GSA needs to set up a 301 redirect that will redirect http://gsa.gov/portal/content/144479 to open.gsa.gov/developer

cc @mboone

**Comment by saracope** [comment]
Closing out.
