### ISSUE TITLE
Migrate and update the developer TOS

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#19]
http://gsa.gov/portal/content/162631 should be reviewed with the [model developer terms of service](https://github.com/GSA/API-Resources/tree/master/developer_tos#readme) in mind.  The content should then be moved to open.gsa.gov.  

@adelevie - any interest in taking a crack at that?

**Comment by adelevie** [comment]
On it.

**Comment by adelevie** [comment]
Taking notes here: https://github.com/adelevie/gsa-tos-notes/commit/5728f1f329b851fc0bdb7d3cbebd7abbebe4dc91

**Comment by gbinal** [comment]
Great progress - go for a pull request whenever you're ready.

**Comment by saracope** [comment]
Closing out here, will address with the team.
