### ISSUE TITLE
Phase out CFPB material 

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#23]
- Fonts
- Images on homepage
- what else?

**Comment by gbinal** [comment]
Switching this to [a milestone](https://github.com/GSA/open.gsa.gov/milestones/Deprecate%20CFPB%20artifacts).

**Comment by gbinal** [comment]
Pinging some of the fantastic CFPB team behind `cfpb.github.io`.  

I've told a few of your team in passing, but wanted to reach out further since GSA is deepening its [re-use and evangelism](http://18f.github.io/API-All-the-X/pages/open_source_documentation) around your great opensource work.  

In this case, `open.gsa.gov` is building from your good work with `cfpb.github.io`.  I recognize that we need to do a lot of cleanup and am spinning up issues in [the abovementioned milestone](https://github.com/GSA/open.gsa.gov/milestones/Deprecate%20CFPB%20artifacts) to that end.  

We disabled some of the more advanced functionality you've built but hope to add it back in as we get up game, but in the meantime, please accept our thanks and appreciation.  We're still working on it but are sure to miss things - please holler anytime with issues or pull requests.   Again - thank you.  

@himedlooff, @scotchester, @ssimpson, @stephanieosan, @iuloshi, @marcesher, @cmc333333, @ascott1, @contolini,

**Comment by contolini** [comment]
![excited-ron-swanson](https://cloud.githubusercontent.com/assets/1060248/6278258/915a873a-b863-11e4-8740-bc685b3cfcb5.gif)

**Comment by Scotchester** [comment]
Thanks, Greg :) We appreciate your kind words.

I'd like to acknowledge that we have long intended to do even more with <cfpb.github.io>. Some of my time has recently freed up and I hope that I will be able to tackle some things like:
- A proper archive of articles
- Project overview pages
- Lightweight navigation to the above

I'm not sure how much of the codebase you are reusing, but please let us know if you have any particular feature requests. And likewise, we'd be more than happy to accept issues and PRs! :)

:muscle: :computer: :us:

**Comment by stephanieosan** [comment]
This made our day yesterday! Thank you :)

**Comment by gbinal** [comment]
Some other notes from #3 I need to take into account:  
- [ ] Process homepage file
- [ ] Process terms file
- [ ] Process copying file
- [ ] Process Contributing file
- [ ] Consider the gitignore/gitmodules files
- [ ] Address fonts
- [ ] posts layout
- [ ] Consider a simple homepage that links to Code, APIs, and Data
- [ ] favicon
- [ ] footer could look better

**Comment by mebates** [comment]
I'd recommend replacing the green field with a color more in line with GSA's products. (blue or gray?)

**Comment by saracope** [comment]
Closing out since we are redesigning the site.
