### ISSUE TITLE
Deprecate the legacy data.json location

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#24]
When #4 and #15 are successfully closed, we can deprecate the legacy data.json file location.  

This should involve: 
- [x] Checking with the data.gov team to ensure that http://open.gsa.gov/data.json can be successfully harvested.  
- [x] Ensure that the latest edits to the public data listing have been published to http://open.gsa.gov/data.json.  
- [ ] Remove http://gsa.gov/data.json
- [ ] Ensure that http://gsa.gov/data.json and http://www.gsa.gov/data.json point to http://open.gsa.gov/data.json.  
- [x] Ask the data.gov team whether they want the harvest to point to http://gsa.gov/data.json or http://open.gsa.gov/data.json, though either should work.  

cc @mboone, @philipashlock, @rebeccawilliams

**Comment by afeld** [comment]
Looks like this might be done?

**Comment by Ryandaydev** [comment]
Closing old issue.
