### ISSUE TITLE
Replace round images on homepage

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#25]
Could be done by overwriting the 150x150 images in [this folder](https://github.com/GSA/open.gsa.gov/tree/gh-pages/img).  

![screen shot 2015-02-19 at 5 33 56 pm](https://cloud.githubusercontent.com/assets/633088/6277547/8125c380-b85d-11e4-85c2-dc4db3552474.png)

**Comment by JSGGSA** [comment]
@gbinal Would you mind replacing the files with the ones I just sent you. I have a feeling its easier in the desktop version. Note: right now the images are 300x300. I can fix them and resend if you want.

**Comment by gbinal** [comment]
Sure thing - one sec.

**Comment by gbinal** [comment]
Yeah - I think they need to be resized to 150x150.  Otherwise, we'll have to code some,which would be harder.  

![screen shot 2015-02-25 at 4 00 49 pm](https://cloud.githubusercontent.com/assets/633088/6380426/92d2f8d8-bd07-11e4-878d-b5adfa3b7f89.png)

**Comment by gbinal** [comment]
@JSGGSA - any luck making new ones?

**Comment by JSGGSA** [comment]
@gbinal Yes I emailed the new ones in the same chain as before. I'll resend so they go to the top of your inbox.

**Comment by gbinal** [comment]
Sorry - my bad.  

Uploaded the images and they're the right size and look good.  I'm going to go ahead and close this issue though I opened up #29 for a small followup if you get a chance, @JSGGSA.  

![screen shot 2015-02-26 at 2 07 53 pm](https://cloud.githubusercontent.com/assets/633088/6399586/5c7f87be-bdc1-11e4-973e-542448e2689a.png)
