### ISSUE TITLE
Tighten up round images on homepage 

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#29]
They are slightly off center.  My suggestion would be to redo them them without the surrounding circles being in the images.  

![screen shot 2015-02-26 at 2 07 53 pm](https://cloud.githubusercontent.com/assets/633088/6399536/fabe9a06-bdc0-11e4-93ca-2f2ec7e4fd47.png)

**Comment by JSGGSA** [comment]
I uploaded new images and I believe they look correct now.
![image](https://cloud.githubusercontent.com/assets/10743420/6690661/4366ed22-cc98-11e4-84ea-43b5c31dd32b.png)

**Comment by gbinal** [comment]
Looks great!  I'll close the issue.
