### ISSUE TITLE
Better invite forum participation

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#32]

**Comment by Ryandaydev** [comment]
@gbinal Can you provide any more explanation on this? We are cleaning up issues for next week's hackathon, which will be working on a redesign to this site.

**Comment by gbinal** [comment]
This issue was referring to trying to engage the [public listserve](https://groups.google.com/forum/#!forum/gsa-data) to jump start it.  Along the lines of #5, though, this group will need to decide if it's going to use it or not.

**Comment by saracope** [comment]
We have an open issue for that on the redesign repo. This can be closed out. Thanks.
