### ISSUE TITLE
Update DigitalGov Search API link

### ISSUE THREAD

**Issue by afeijoo** [GSA/gsa.github.io#35]
Link on http://open.gsa.gov/developer/ should be to https://search.usa.gov/login, not http://gsa.github.io/developer.

Suggested edit to description, "Provides DigitalGov Search customers their search results in JSON. Sign in with a .gov or .mil email is required."

**Comment by gbinal** [comment]
URL changed with https://github.com/GSA/open.gsa.gov/pull/36/commits

**Comment by gbinal** [comment]
The description change should be coming soon.

**Comment by Ryandaydev** [comment]
Looks like this has been updated. Closing issue.
