### ISSUE TITLE
Migrate gsa's data.json file to here

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#4]

**Comment by gbinal** [comment]
[This is done](http://open.gsa.gov/data.json), however I need to ensure that the new open.gsa.gov/data page can consume it.

**Comment by konklone** [comment]
And `gsa.gov/data.json` would redirect to this?

**Comment by gbinal** [comment]
Correct - See #24.

**Comment by gbinal** [comment]
Issue #24 can take it from here, so I'm going to go ahead and close this.
