### ISSUE TITLE
update the references to the May 8 hackathon

### ISSUE THREAD

**Issue by gbinal** [GSA/gsa.github.io#43]
http://open.gsa.gov/ and http://open.gsa.gov/Digital-Innovation-Hackathon/ still refer to the event at upcoming.  

cc @JSGGSA, @mboone

**Comment by JSGGSA** [comment]
@gbinal @mboone  I just removed the save the date references and updated our page to a past tense narrative. I also moved the completed projects further up on the page.

**Comment by gbinal** [comment]
I'll go ahead and close this but recommend putting something else in the news section in the top right of the homepage.  It's pretty bare without it.
