### ISSUE TITLE
As a GSA staff member, I want to know how to publish data

### ISSUE THREAD

**Issue by afeld** [GSA/gsa.github.io#50]
I was trying to publish the IT Standards Profile list (https://github.com/GSA/data/pull/37), and was surprised at how many places I had to jump around and people I needed to ask in order to figure out how to get something published "the right way"...and I'm technical and almost competent! Would be great to have a place to point people who have the question "I have some data that I want to make available...what do I do?" Basically, how do we remove the friction from publishing data (responsibly) at GSA?

https://github.com/GSA/open.gsa.gov/pull/48 started to address this, but I think we can go farther with it.

**Comment by saracope** [comment]
Copied this over to the redesign repo. Thanks!
