### ISSUE TITLE
Getting 404 on Data Center Consolidation API

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/gsa.github.io#57]
I get a 404 trying to follow this link on open.gsa.gov/developer.

Data Center Consolidation API

URL is:
https://explore.data.gov/developers/docs/federal-data-center-consolidation-initiative-fdcci-data-center-closings-2010-2013

**Comment by gbinal** [comment]
It appears that the API is no longer being offered.  All I see in GSA's public data listing is [this](https://catalog.data.gov/dataset/fed-data-center-consolidation-initiative-fdcci-data-center-closings-2010-2015), though it's a static download, not an API.

**Comment by Ryandaydev** [comment]
Issue closed with pull request #59
