### ISSUE TITLE
Getting 404 on 2 my.usa.gov API links

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/gsa.github.io#58]
I get a 404 trying to follow these links too:

MyUSA Citizen API
https://my.usa.gov/developer/

MyGov Discovery API
https://discovery.my.usa.gov/

**Comment by gbinal** [comment]
@rdgsa - it appears that both of those have been overtaken by https://alpha.my.usa.gov/developer.  I'd remove them and add it in.

**Comment by afeld** [comment]
I would remove the link entirely, due to https://github.com/18F/myusa/issues/762.

**Comment by Ryandaydev** [comment]
Issue closed with pull request #59.
