### ISSUE TITLE
Add Non-.gov URL API

### ISSUE THREAD

**Issue by afeijoo** [GSA/gsa.github.io#62]
Add http://search.digitalgov.gov/developer/govt-urls.html to http://open.gsa.gov/developer.

A potential slug is, "This API allows you to find government URLs that don't end in .gov or .mil. URLs are searchable by keyword, state, or scope."

**Comment by Ryandaydev** [comment]
Thanks, we are working on a site redesign so I'm closing the issue here and moving to that repo.

https://github.com/GSA/open-gsa-redesign/issues/35

**Comment by gbinal** [comment]
Thanks for tracking these as issues, @rdgsa.  It's a big help!  

A question - what's the current ETA on this redesign.  Given how easily we can edit the legacy site (I'm happy to file a PR), if it's going to be more than a month or so, could I recommend we still add this here?  

This API is relevant to some recent policy that rolled out and is also just good stuff and worth getting out there anyway.
